### ISSUE TITLE
clean_corpus.R not pulling out all French affiliations

### ISSUE THREAD

**Issue by jmarsicek** [EarthCubeGeochron/IRDDive#5]
In clean_corpus.R, line 32 is not getting rid of all French affiliations (paper _Evidence for tropical South Pacific climate change during the Younger Dryas and the Bølling–Allerød from geochemical records of fossil Tahiti corals_ still shows up in the leaflet map after cleaning and plotting when it shouldn't. Any ideas on this?

Additionally, I added a line as I was playing with the function to get rid of the paper from central Asia by adding line 33 in clean_corpus.R, but again, in the leaflet map it still shows up. I'm curious if @SimonGoring you have any thoughts as to why this is not getting pulled. 

Lastly, reference_drops (line 70) in clean_corpus.R isn't actually pulling out any papers with IRD in the references, but I will play around with this a bit more. Just putting it here as a reminder.

**Comment by SimonGoring** [comment]
The paper *Evidence for tropical South Pacific climate change during the Younger Dryas and the Bølling–Allerød from geochemical records of fossil Tahiti corals* has a `_gddid` of `54cc6b86e138236bcc92a002` .  The paper was not detected because IRD (the institution) was referred to twice, once with an address which was caught by the `france` regex, and another one that missed the reference to CNRS but contained a web reference.

This is all fixed in commit 5b53f0d3ab5823eba99b68d5a191fd75de8bac60.

**Comment by SimonGoring** [comment]
This does not resolve the reference drops though.  I will raise this in a new issue.
